version: '3'
services:
  cassandra:
    image: 'bitnami/cassandra:3'
    ports:
    - '7000:7000'
    - '9042:9042'
    volumes:
    - 'cassandra_data:/bitnami'
    - ./..:/mnt/workspace/
    environment:
    - CASSANDRA_SEEDS=cassandra
    - CASSANDRA_PASSWORD_SEEDER=yes
    - CASSANDRA_PASSWORD=cassandra
  kafka:
    build:
      context: ./kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./..:/mnt/workspace/
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
volumes:
  cassandra_data:
    driver: local